Repository OpenCSGs/csghub, pull requests merged in 2024-08, with the labels that each got.

#391 Fix last commit init issue in file list
  app/javascript/components/shared/FileList.vue
Labels: local-verified

#390 合集UI优化
  app/javascript/components/collections/CollectionCard.vue
  app/javascript/components/collections/CollectionCards.vue
  app/javascript/components/collections/CollectionIndex.vue
  app/javascript/components/collections/CollectionsAddRepo.vue
  app/javascript/components/collections/CollectionsDetail.vue
  app/javascript/components/collections/CollectionsRepoList.vue
  app/javascript/components/navbar/Collection.vue
  app/views/collections/index.html.erb
  config/locales/en_js/all.js
  config/locales/en_js/collections.js
  config/locales/zh_js/all.js
  config/locales/zh_js/collections.js
  public/images/collection_half_cirle.png
  public/images/search_circle_bg.png
Labels: local-verified

#392 Bug fix space logs not shown
  app/javascript/components/application_spaces/ApplicationSpaceDetail.vue
Labels: local-verified

#394 Lazy load repo tab panel component
  app/javascript/components/shared/TabContainer.vue
Labels: local-verified

#397 Space logs not shown error(phase2)
  app/javascript/components/application_spaces/ApplicationSpaceDetail.vue
Labels: local-verified

#393 change flex col into row
  app/javascript/components/shared/HeaderTags.vue
Labels: local-verified

#367 在admin中的模型编辑添加搜索模型
  app/javascript/components/new_admin/models/AdminModelEdit.vue
Labels: local-verified

#398 Fix collection cards style
  app/javascript/components/collections/CollectionCards.vue
Labels: local-verified

#399 Update owner url
  app/javascript/components/application_spaces/ApplicationSpaceDetail.vue
  app/javascript/components/shared/RepoDetail.vue
Labels: local-verified

#396 调整repo header样式
  app/javascript/components/shared/RepoHeader.vue
Labels: local-verified

#377 数据集parquet jwt迁移
  app/controllers/concerns/api/repo_validation.rb
  app/controllers/internal_api/datasets_controller.rb
  app/javascript/components/shared/RepoSummary.vue
  app/services/starhub/api.rb
  config/routes.rb
Labels: local-verified

#378 将关联repo转化为jwt
  app/controllers/internal_api/codes_controller.rb
  app/controllers/internal_api/datasets_controller.rb
  app/controllers/internal_api/models_controller.rb
  app/javascript/components/shared/RepoSummary.vue
  app/services/starhub/code_apis.rb
  app/services/starhub/dataset_apis.rb
  app/services/starhub/model_apis.rb
  app/services/starhub/shared_repo_apis.rb
  config/routes.rb
Labels: local-verified

#404 Collections downloads fix
  app/javascript/components/collections/CollectionCard.vue
Labels: local-verified

#402 Fetch user token when clone modal open
  app/javascript/components/shared/RepoClone.vue
Labels: local-verified

#405 Optimzie Wechat like third party login logics
  app/controllers/application_controller.rb
  app/helpers/sessions_helper.rb
  app/javascript/components/navbar/TheNavbar.vue
  app/javascript/components/user_settings/ProfileEdit.vue
  app/views/layouts/application.html.erb
  config/locales/en_js/navbar.js
  config/locales/en_js/profile.js
  config/locales/en_yml/errors_page.en.yml
  config/locales/zh_js/navbar.js
  config/locales/zh_js/profile.js
  config/locales/zh_yml/errors_page.zh.yml
Labels: local-verified

#406 Fix new finetune select bug
  app/javascript/components/finetune/NewFinetune.vue
Labels: local-verified

#408 CollectionRepoList downloads
  app/javascript/components/collections/CollectionsRepoList.vue
Labels: local-verified

#410 Update endpoint api params
  app/javascript/components/endpoints/EndpointPlayground.vue
  app/javascript/components/endpoints/playground/TestEndpoint.vue
Labels: local-verified

#411 Show deploy and finetune button when model support
  app/javascript/components/shared/RepoClone.vue
Labels: local-verified

#412 Bug fix for repo likes
  app/javascript/components/shared/RepoHeader.vue
Labels: local-verified

#403 docs: add Japanese README
  README.md
  docs/readme_cn.md
  docs/readme_en.md
  docs/readme_ja.md
Labels: help wanted

#413 Fix resources select
  app/javascript/components/application_spaces/ApplicationSpaceSettings.vue
  app/javascript/components/endpoints/EndpointSettings.vue
  app/javascript/components/finetune/FinetuneSettings.vue
Labels: local-verified

#415 Fix org edit value init
  app/javascript/components/organizations/OrganizationEdit.vue
Labels: local-verified

#416 Fix error message
  app/javascript/components/application_spaces/ApplicationSpaceSettings.vue
  app/javascript/components/application_spaces/NewApplicationSpace.vue
  app/javascript/components/codes/CodeSettings.vue
  app/javascript/components/codes/NewCode.vue
  app/javascript/components/collections/CollectionsAddRepo.vue
  app/javascript/components/datasets/DatasetSettings.vue
  app/javascript/components/datasets/NewDataset.vue
  app/javascript/components/endpoints/EndpointSettings.vue
  app/javascript/components/models/ModelSettings.vue
  app/javascript/components/models/NewModel.vue
  app/javascript/components/organizations/InviteMember.vue
  app/javascript/components/organizations/NewOrganization.vue
  app/javascript/components/organizations/OrgMemberRoleEditDialog.vue
  app/javascript/components/organizations/OrganizationEdit.vue
  app/javascript/components/shared/RepoSummary.vue
Labels: local-verified

#417 Collections hide likes
  app/javascript/components/shared/RepoHeader.vue
Labels: local-verified

#414 Csghub fix org edit admin
  app/javascript/components/organizations/InviteMember.vue
  app/javascript/components/organizations/OrganizationDetail.vue
  app/javascript/components/organizations/OrganizationMembers.vue
  app/javascript/components/organizations/OrganizationSettings.vue
Labels: local-verified

#418 Fix lfs file download
  app/javascript/components/shared/FileList.vue
Labels: local-verified

#420 非当前profile不显示微调实例列表
  app/javascript/components/shared/ProfileRepoList.vue
Labels: local-verified

#421 Bug fix: text and clone refer links
  app/javascript/components/datasets/DatasetRelationsCard.vue
  app/javascript/components/shared/RepoClone.vue
  config/locales/en_js/datasets.js
  config/locales/zh_js/datasets.js
Labels: local-verified

#419 Fix org edit homepage
  app/javascript/components/organizations/OrganizationEdit.vue
Labels: local-verified

#422 Update commit id styles
  app/javascript/components/shared/RepoCommits.vue
Labels: local-verified

#423 Fix model relations card icon
  app/javascript/components/models/ModelRelationsCard.vue
Labels: local-verified

#424 Update space code model i18n icon
  app/javascript/components/application_spaces/SpaceRelationsCard.vue
  app/javascript/components/codes/CodeRelationsCard.vue
  app/javascript/components/models/ModelRelationsCard.vue
  config/locales/en_js/codes.js
  config/locales/en_js/models.js
  config/locales/en_js/spaces.js
  config/locales/zh_js/codes.js
  config/locales/zh_js/models.js
  config/locales/zh_js/spaces.js
Labels: local-verified

#425 Only gpu for finetune resources
  app/javascript/components/finetune/NewFinetune.vue
Labels: local-verified

#427 修复组织详情页布局
  app/javascript/components/organizations/OrganizationDetail.vue
Labels: local-verified

#428 Update endpoint playground api example
  app/javascript/components/endpoints/playground/ApiExample.vue
  app/javascript/components/shared/viewers/CodeViewer.vue
Labels: local-verified

#426 Check permission for repo detail api
  app/javascript/components/shared/RepoDetail.vue
  app/javascript/packs/usePermissionCheck.js
Labels: local-verified

#429 Fix endpoint detail
  app/controllers/endpoints_controller.rb
  app/javascript/components/endpoints/EndpointDetail.vue
  app/javascript/components/endpoints/EndpointItem.vue
Labels: local-verified

#430 Fix bug of fetching endpoint billing detail
  app/javascript/components/shared/BillingDetail.vue
Labels: local-verified

#431 update repo card style including font、color、gap and padding
  app/javascript/components/application_spaces/ApplicationSpaceItem.vue
  app/javascript/components/endpoints/EndpointItem.vue
  app/javascript/components/shared/FinetuneItem.vue
  app/javascript/components/shared/RepoCards.vue
  app/javascript/components/shared/RepoItem.vue
Labels: local-verified

#434 Runtime framework bug fix
  app/javascript/components/endpoints/NewEndpoint.vue
  app/javascript/components/user_settings/Profile.vue
Labels: local-verified

#435 add finetune margin top and update label font color
  app/javascript/components/shared/ProfileRepoList.vue
Labels: local-verified

#436 Use cookies for session logic
  app/helpers/sessions_helper.rb
Labels: local-verified

#437 Add link for file list commit
  app/javascript/components/shared/FileList.vue
Labels: local-verified

#438 Redirect to login page when jwt blank
  app/controllers/sessions_controller.rb
  app/javascript/packs/refreshJWT.js
Labels: local-verified

#439 Get endpoint detail after status running
  app/javascript/components/endpoints/EndpointDetail.vue
Labels: local-verified

#441 Endpoint runtime framework update bug fix
  app/javascript/components/endpoints/EndpointDetail.vue
  app/javascript/components/endpoints/EndpointSettings.vue
  app/javascript/components/finetune/FinetuneDetail.vue
  app/javascript/components/shared/BillingDetail.vue
Labels: local-verified

#443 Fix endpoint api example issues
  app/javascript/components/endpoints/EndpointDetail.vue
  app/javascript/components/endpoints/EndpointPage.vue
  app/javascript/components/endpoints/playground/ApiExample.vue
Labels: local-verified

#444 Optimize jwt token refresh
  app/controllers/internal_api/users_controller.rb
  app/helpers/sessions_helper.rb
  app/javascript/components/navbar/TheNavbar.vue
  app/javascript/packs/refreshJWT.js
  config/routes.rb
Labels: local-verified

#445 Fix endpoint item hardware type
  app/javascript/components/endpoints/EndpointItem.vue
Labels: local-verified

#446 Add billing detail refresh effect
  app/javascript/components/shared/BillingDetail.vue
Labels: local-verified

#449 More optimization for jwt refresh
  app/javascript/packs/refreshJWT.js
Labels: local-verified

#451 Optimize user token check and fix refresh token API
  app/controllers/internal_api/users_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/javascript/packs/jwtFetch.js
  app/javascript/packs/refreshJWT.js
  app/services/starhub/api.rb
  config/routes.rb
  package.json
  yarn.lock
Labels: local-verified

#454 Fix endpoint playground
  app/javascript/components/endpoints/EndpointPage.vue
  app/javascript/components/endpoints/EndpointPlayground.vue
  app/javascript/components/endpoints/playground/ApiExample.vue
Labels: local-verified

#455 Fix finetune route
  config/routes.rb
Labels: local-verified

#461 Fix jwt refresh logic bug
  app/javascript/packs/refreshJWT.js
Labels: local-verified

#463 Update repo header avatar
  app/javascript/components/application_spaces/ApplicationSpaceDetail.vue
  app/javascript/components/endpoints/EndpointPlayground.vue
  app/javascript/components/shared/RepoDetail.vue
  app/views/application_spaces/show.html.erb
  app/views/codes/show.html.erb
  app/views/datasets/show.html.erb
  app/views/models/show.html.erb
Labels: local-verified

#465 Update frameworks filter
  app/javascript/components/application_spaces/AppStatus.vue
  app/javascript/components/endpoints/EndpointSettings.vue
  app/javascript/components/endpoints/NewEndpoint.vue
  app/javascript/components/finetune/NewFinetune.vue
Labels: local-verified

#473 Add missing locale for dataset
  config/locales/en_js/datasets.js
  config/locales/zh_js/datasets.js
Labels: local-verified

#475 Fix url protocal for repo clone
  app/javascript/components/shared/RepoClone.vue
Labels: local-verified

#476 限定项目列表页repocard为双列布局
  app/javascript/components/shared/RepoCards.vue
Labels: local-verified

#478 Invite New Member: Click to Hide User List and Clear Username Input
  app/javascript/components/organizations/InviteMember.vue
Labels: local-verified

#477 Fix repo tag i18n
  app/javascript/components/datasets/DatasetSettings.vue
  app/javascript/components/models/ModelSettings.vue
Labels: local-verified

#442 Csghub collections
  app/controllers/collections_controller.rb
  app/javascript/components/collections/CollectionsDetail.vue
  app/javascript/components/collections/NewCollection.vue
  app/javascript/components/shared/ProfileRepoList.vue
  app/javascript/components/shared/RepoHeader.vue
  app/views/collections/new.html.erb
Labels: local-verified

#462 Remove repo form collections
  app/javascript/components/collections/CollectionsAddRepo.vue
  app/javascript/components/collections/CollectionsDetail.vue
  app/javascript/components/collections/CollectionsRepoList.vue
  config/locales/en_js/collections.js
  config/locales/zh_js/collections.js
  public/images/icons/trash.svg
Labels: local-verified

#479 Org default logo
  app/javascript/components/organizations/OrganizationDetail.vue
  app/javascript/components/user_settings/Profile.vue
Labels: local-verified

#480 Fix button layout
  app/javascript/components/collections/AddToCollections.vue
  app/javascript/components/shared/RepoClone.vue
  app/javascript/components/shared/RepoTabs.vue
Labels: local-verified

#482 移动端文件列表页面适配
  app/javascript/components/shared/FileList.vue
Labels: local-verified

#483 Fix new finetune fetch resources bug
  app/javascript/components/finetune/NewFinetune.vue
Labels: local-verified

#485 Revert license info display
  app/controllers/internal_api/admin/application_controller.rb
  app/controllers/internal_api/admin/system_config_controller.rb
  app/javascript/components/new_admin/system_configs/AdminSystemConfig.vue
  app/javascript/components/shared/RepoSummary.vue
  app/javascript/components/shared/RepoTabs.vue
  app/models/system_config.rb
  config/locales/en_js/all.js
  config/locales/zh_js/all.js
  config/routes.rb
  db/migrate/20240115085646_add_license_info_to_system_config.rb
  db/schema.rb
Labels: local-verified

#484 Revert model provenance functions for open source
  app/javascript/components/shared/RepoDetail.vue
  app/javascript/components/shared/RepoHeader.vue
  config/locales/en_js/all.js
  config/locales/zh_js/all.js
Labels: local-verified

#494 fix Firefox browser compatibility
  app/javascript/components/collections/CollectionIndex.vue
Labels: local-verified

#496 Csghub new collections default public.
  app/javascript/components/collections/NewCollection.vue
  config/locales/en_js/collections.js
  config/locales/zh_js/collections.js
Labels: local-verified

#493 Csghub org invite bug fix
  app/javascript/components/organizations/InviteMember.vue
  app/javascript/components/organizations/OrganizationDetail.vue
  app/javascript/components/organizations/OrganizationMembers.vue
Labels: local-verified

#495 Login logic optimization
  app/assets/stylesheets/application.tailwind.css
  app/controllers/errors_controller.rb
  app/controllers/internal_api/users_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/javascript/application.js
  app/javascript/components/navbar/TheNavbar.vue
  app/javascript/components/shared/BillingDetail.vue
  app/javascript/components/user_settings/Profile.vue
  app/javascript/packs/jwtFetch.js
  app/javascript/packs/refreshJWT.js
  app/javascript/packs/useFetchApi.js
  app/services/starhub/api.rb
  app/views/errors/404.html.erb
  app/views/errors/login_failed.html.erb
  config/locales/en_js/user_sessions.js
  config/locales/errors_page.en.yml
  config/locales/errors_page.zh.yml
  config/locales/zh_js/user_sessions.js
  config/routes.rb
  public/images/error_page_bg.png
  public/images/icons/login_failed.svg
Labels: local-verified

#497 Fix lfs file download in file list page
  app/javascript/components/shared/FileList.vue
Labels: local-verified

#500 Csghub collections card hover show del
  app/javascript/components/application_spaces/NewApplicationSpace.vue
  app/javascript/components/collections/CollectionsRepoList.vue
Labels: local-verified

#499 Change AddToCollections display
  app/javascript/components/collections/AddToCollections.vue
  app/javascript/components/shared/RepoTabs.vue
Labels: local-verified

#492 tab container样式与设计稿同步
  app/javascript/components/shared/TabContainer.vue
Labels: local-verified

#505 Fix repo cards
  app/javascript/components/shared/RepoCards.vue
Labels: local-verified

#506 Fix statements api
  app/javascript/components/shared/BillingDetail.vue
Labels: local-verified

#504 Remove endpoint local validation
  app/controllers/endpoints_controller.rb
  app/javascript/components/endpoints/EndpointDetail.vue
  app/views/endpoints/show.html.erb
Labels: local-verified

#507 Need login to access dataset
  app/controllers/datasets_controller.rb
Labels: local-verified

#508 Fix filelist style
  app/javascript/components/shared/FileList.vue
Labels: local-verified

#509 Fix long name bug
  app/javascript/components/collections/CollectionCards.vue
  app/views/profile/index.html.erb
  app/views/profile/likes.html.erb
Labels: local-verified

#510 Clear cookies in fronted when logout
  app/javascript/components/navbar/TheNavbar.vue
Labels: local-verified

#511 Update hover focus style
  app/javascript/components/collections/CollectionCards.vue
  app/javascript/components/shared/RepoItem.vue
Labels: local-verified

#488 更新headertags样式
  app/javascript/components/shared/HeaderTags.vue
  app/javascript/components/tags/TagItem.vue
Labels: local-verified

#514 change table header name in billing page
  config/locales/en_js/billing.js
  config/locales/zh_js/billing.js
Labels: local-verified

#513 Csghub collections btn fix
  app/javascript/components/collections/AddToCollections.vue
  app/javascript/components/shared/RepoClone.vue
  app/javascript/components/shared/RepoTabs.vue
Labels: local-verified

#520 replace tags svg icon as same border
  public/images/tags/action-detection.svg
  public/images/tags/audio-classification.svg
  public/images/tags/auto-speech-recognition.svg
  public/images/tags/autonomous-driving.svg
  public/images/tags/conversational.svg
  public/images/tags/document-segmentation.svg
  public/images/tags/face-detection.svg
  public/images/tags/face-image-generation.svg
  public/images/tags/face-recognition.svg
  public/images/tags/feature-extraction.svg
  public/images/tags/fill-mask.svg
  public/images/tags/image-captioning.svg
  public/images/tags/image-classification.svg
  public/images/tags/image-editing.svg
  public/images/tags/image-generation.svg
  public/images/tags/image-object-detection.svg
  public/images/tags/image-segmentation.svg
  public/images/tags/image-super-resolution.svg
  public/images/tags/image-text-retrieval.svg
  public/images/tags/image-to-image.svg
  public/images/tags/image-to-text.svg
  public/images/tags/multiple-choice.svg
  public/images/tags/named-entity-recognition.svg
  public/images/tags/nli.svg
  public/images/tags/object-detection.svg
  public/images/tags/object-tracking.svg
  public/images/tags/ocr.svg
  public/images/tags/part-of-speech.svg
  public/images/tags/question-answering.svg
  public/images/tags/relation-extraction.svg
  public/images/tags/semantic-segmentation.svg
  public/images/tags/sentence-similarity.svg
  public/images/tags/sentiment-classification.svg
  public/images/tags/skin-retouching.svg
  public/images/tags/speech-signal-process.svg
  public/images/tags/summarization.svg
  public/images/tags/table-question-answering.svg
  public/images/tags/text-classification.svg
  public/images/tags/text-generation.svg
  public/images/tags/text-retrieval.svg
  public/images/tags/text-summarization.svg
  public/images/tags/text-to-image.svg
  public/images/tags/text-to-speech.svg
  public/images/tags/token-classification.svg
  public/images/tags/translation.svg
  public/images/tags/video-captioning.svg
  public/images/tags/video-classification.svg
  public/images/tags/video-detection.svg
  public/images/tags/video-generation.svg
  public/images/tags/video-segmentation.svg
  public/images/tags/video-super-resolution.svg
  public/images/tags/visual-grounding.svg
  public/images/tags/visual-question-answering.svg
  public/images/tags/word-segmentation.svg
  public/images/tags/zero-shot.svg
Labels: local-verified

#481 finetune详情页关联模型支持点击跳转
  app/javascript/components/shared/RepoHeader.vue
Labels: local-verified

#523 Update role refresh
  app/javascript/components/organizations/OrgMemberRoleEditDialog.vue
Labels: local-verified

#521 StarshipAccessTokenSettings button i18n
  app/javascript/components/user_settings/StarshipAccessTokenSettings.vue
Labels: local-verified

#524 Csghub collections new details refactor
  app/javascript/components/collections/CollectionIndex.vue
  app/javascript/components/collections/CollectionsDetail.vue
  app/javascript/components/collections/NewCollection.vue
Labels: local-verified

#498 用户的用户名和email 需要支持同时更新
  app/javascript/components/popup/UpdateUsername.vue
  app/javascript/components/shared/RepoCards.vue
  config/locales/en_js/all.js
  config/locales/en_js/profile.js
  config/locales/zh_js/all.js
  config/locales/zh_js/profile.js
Labels: local-verified

#527 Update HeaderTags.vue
  app/javascript/components/shared/HeaderTags.vue
  app/javascript/components/tags/TagItem.vue
Labels: local-verified

#533 Update README.md
  README.md
Labels: contribution

#534 English string modification for model, dataset, code, application space listing page
  app/javascript/components/shared/RepoCards.vue
  config/locales/en_js/all.js
  config/locales/en_js/codes.js
  config/locales/en_js/datasets.js
  config/locales/en_js/models.js
  config/locales/en_js/spaces.js
Labels: local-verified

#537 refactoring 404 page with new ui
  public/404.html
Labels: local-verified

#539 refactoring 404.html.erb with new ui
  app/views/errors/404.html.erb
  config/locales/en_yml/errors_page.en.yml
  config/locales/errors_page.zh.yml
Labels: local-verified

#542 update locale file
  app/javascript/components/application_spaces/ApplicationSpaceSettings.vue
  app/javascript/components/codes/CodeSettings.vue
  app/javascript/components/collections/CollectionsSettings.vue
  app/javascript/components/datasets/DatasetSettings.vue
  app/javascript/components/models/ModelSettings.vue
  config/locales/en_js/all.js
  config/locales/en_js/application_spaces.js
  config/locales/en_js/codes.js
  config/locales/en_js/collections.js
  config/locales/en_js/datasets.js
  config/locales/en_js/models.js
  config/locales/zh_js/application_spaces.js
  config/locales/zh_js/codes.js
  config/locales/zh_js/collections.js
  config/locales/zh_js/datasets.js
  config/locales/zh_js/models.js
Labels: local-verified

#545 微调实例里面也有Chat界面，应该也添加同样的免责声明
  app/javascript/components/endpoints/playground/TestEndpoint.vue
Labels: local-verified

#551 RepoClone no space
  app/javascript/components/shared/RepoClone.vue
Labels: local-verified

#550 RepoClone use location.origin
  app/javascript/components/shared/RepoClone.vue
Labels: local-verified

#553 Resolve internal api support more image types
  app/controllers/concerns/blob_content_helper.rb
  app/helpers/application_helper.rb
Labels: local-verified

#554 Repo setting i18n
  config/locales/zh_js/application_spaces.js
  config/locales/zh_js/codes.js
  config/locales/zh_js/datasets.js
Labels: local-verified
