Repository OpenCSGs/csghub, pull requests merged in 2025-05, with the labels that each got.

#1116 feat(model): model metadata
  frontend/public/images/icons/metadata_GGUF.svg
  frontend/public/images/icons/metadata_Safetensors.svg
  frontend/public/images/icons/vertical_divider2.svg
  frontend/src/components/__tests__/endpoints/NewEndpoint.spec.js
  frontend/src/components/endpoints/NewEndpoint.vue
  frontend/src/components/models/ModelMetadata.vue
  frontend/src/components/models/metadata/MetaItem.vue
  frontend/src/components/navbar/Navbar.vue
  frontend/src/components/shared/RepoSummary.vue
  frontend/src/components/shared/RepoTabs.vue
  frontend/src/locales/en_js/all.js
  frontend/src/locales/en_js/endpoints.js
  frontend/src/locales/en_js/models.js
  frontend/src/locales/zh_js/all.js
  frontend/src/locales/zh_js/endpoints.js
  frontend/src/locales/zh_js/models.js
  frontend/src/stores/RepoDetailStore.js
Labels: local-verified

#1118 feat(evaluations): add form validation on submit
  frontend/src/components/__tests__/evaluations/NewEvaluation.spec.js
  frontend/src/components/evaluations/NewEvaluation.vue
Labels: local-verified

#1126 feat(middleware): skip authentication for static files
  internal/middleware/auth_middleware.go
Labels: local-verified

#1133 feat(repo-item): add task tag icon support
  frontend/src/components/shared/RepoItem.vue
Labels: local-verified, GitLab linked

#1134 feat(admin_serverless): enhance hardware display
  frontend/src/components/admin_next/serverless/AdminServerlessList.vue
Labels: local-verified, GitLab linked

#1146 feat(locales): update navbar text labels
  frontend/src/locales/en_js/navbar.js
  frontend/src/locales/zh_js/navbar.js
Labels: local-verified, GitLab linked

#1139 update styling and button components
  frontend/src/assets/stylesheets/element-plus/button.css
  frontend/src/components/__tests__/datasets/DatasetSettings.spec.js
  frontend/src/components/application_spaces/ApplicationSpaceSettings.vue
  frontend/src/components/codes/CodeSettings.vue
  frontend/src/components/collections/CollectionsSettings.vue
  frontend/src/components/datasets/DatasetSettings.vue
  frontend/src/components/mcp/McpSettings.vue
  frontend/src/components/models/ModelSettings.vue
  frontend/src/components/prompts/PromptsListSettings.vue
Labels: local-verified, GitLab linked

#1145 feat(task_tag): add image text to text svg icon
  frontend/public/images/tags/image-text-to-text.svg
Labels: local-verified, GitLab linked

#1148 feat(task_tag): update task tag icon
  frontend/public/images/tags/biomedicine.svg
  frontend/public/images/tags/protein-structure.svg
  frontend/src/components/shared/RepoItem.vue
Labels: local-verified, GitLab linked

#1151 feat(button): add secondary button styles
  frontend/src/assets/stylesheets/element-plus/button.css
Labels: local-verified, GitLab linked

#1153 feat(endpoints): update validation triggers and params
  frontend/src/components/endpoints/NewEndpoint.vue
  frontend/src/components/evaluations/NewEvaluation.vue
  frontend/src/components/finetune/NewFinetune.vue
Labels: local-verified

#1149 feat(application_spaces): replace space links with component
  frontend/src/components/__tests__/application_spaces/SpaceRelationsCard.spec.js
  frontend/src/components/application_spaces/SpaceRelationsCard.vue
Labels: local-verified, GitLab linked

#1157 feat(admin): enhance UI components and translations
  frontend/src/components/admin_next/models/AdminModelList.vue
  frontend/src/components/admin_next/serverless/AdminServerlessDetail.vue
  frontend/src/components/admin_next/serverless/AdminServerlessList.vue
  frontend/src/components/admin_next/tag_categories/AdminTagCategoriesList.vue
  frontend/src/components/admin_next/tags/AdminTagsList.vue
  frontend/src/components/admin_next/users/AdminUserList.vue
  frontend/src/locales/en_js/admin.js
  frontend/src/locales/zh_js/admin.js
Labels: local-verified, GitLab linked

#1165 feat(application_space_detail): add scroll handling for logs
  frontend/public/images/icons/chevron-down.svg
  frontend/public/images/icons/chevron-up.svg
  frontend/public/images/icons/x-close.svg
  frontend/src/components/application_spaces/ApplicationSpaceDetail.vue
Labels: local-verified, GitLab linked

#1166 feat(EndpointLogs): enhance log display and interaction
  frontend/src/components/endpoints/EndpointLogs.vue
Labels: GitLab linked
