Repository OpenCSGs/csghub, pull requests merged in 2025-06, with the labels that each got.

#1171 feat(pagination): improve button styles and layout
  frontend/src/components/shared/CsgPagination.vue
Labels: local-verified, GitLab linked

#1172 change-repodetail-linktype-to-vue-router
  frontend/src/components/__tests__/endpoints/EndpointDetail.spec.js
  frontend/src/components/__tests__/endpoints/EndpointItem.spec.js
  frontend/src/components/__tests__/finetune/FinetuneDetail.spec.js
  frontend/src/components/application_spaces/ApplicationSpaceDetail.vue
  frontend/src/components/application_spaces/ApplicationSpaceItem.vue
  frontend/src/components/community/CommunityPage.vue
  frontend/src/components/datasets/DatasetSettings.vue
  frontend/src/components/endpoints/EndpointDetail.vue
  frontend/src/components/endpoints/EndpointItem.vue
  frontend/src/components/finetune/FinetuneDetail.vue
  frontend/src/components/mcp/McpItem.vue
  frontend/src/components/models/ModelSettings.vue
  frontend/src/components/resource_console/EvaluationTable.vue
  frontend/src/components/shared/Blob.vue
  frontend/src/components/shared/EditFile.vue
  frontend/src/components/shared/FileList.vue
  frontend/src/components/shared/FinetuneItem.vue
  frontend/src/components/shared/NewFile.vue
  frontend/src/components/shared/RepoCommit.vue
  frontend/src/components/shared/RepoCommits.vue
  frontend/src/components/shared/RepoDetail.vue
  frontend/src/components/shared/RepoFiles.vue
  frontend/src/components/shared/RepoItem.vue
  frontend/src/components/shared/RepoTabs.vue
  frontend/src/components/shared/TabContainer.vue
  frontend/src/components/shared/UploadFile.vue
  frontend/src/stores/RepoTabStore.js
  frontend/src/views/endpoints/show.html
  frontend/src/views/finetunes/show.html
  frontend/src/views/models/show.html
Labels: local-verified

#1176 fix-tab-change-page-flash only work in repo detail
  frontend/src/components/datasets/ParquetViewer.vue
  frontend/src/components/finetune/FinetuneDetail.vue
  frontend/src/components/shared/TabContainer.vue
Labels: local-verified

#1179 feat(RepoCards): improve responsive layout and behavior
  frontend/src/components/__tests__/shared/RepoCards.spec.js
  frontend/src/components/shared/RepoCards.vue
Labels: local-verified, GitLab linked

#1178 feat(navbar): enhance avatar dropdown styling
  frontend/src/components/navbar/Navbar.vue
Labels: GitLab linked

#1183 feat(discussion): add delete discussion feature
  frontend/src/components/community/CommunityMDTextarea.vue
  frontend/src/components/community/DiscussionCard.vue
  frontend/src/components/community/DiscussionCards.vue
  frontend/src/components/community/DiscussionDetails.vue
  frontend/src/components/community/NewCommunityDiscussion.vue
  frontend/src/locales/en_js/community.js
  frontend/src/locales/zh_js/community.js
Labels: local-verified, GitLab linked

#1191 fix-filelist-tree-request-twice
  frontend/src/components/shared/FileList.vue
Labels: local-verified

#1193 feat(RepoSummaryApiExample): make modelId dynamic
  frontend/src/components/shared/RepoSummaryApiExample.vue
Labels: local-verified, GitLab linked

#1189 feat(styles): add Element Plus index.css import
  frontend/src/admin.js
  frontend/src/assets/stylesheets/element-plus/el-message-box.css
  frontend/src/assets/stylesheets/element-plus/index.css
  frontend/src/main.js
Labels: local-verified, GitLab linked

#1195 fix(RepoCommits): update committer name reference
  frontend/src/components/shared/RepoCommits.vue
Labels: local-verified, GitLab linked

#1201 feat(tabs): enhance tab behavior and styles
  frontend/src/components/shared/TabContainer.vue
  frontend/src/style.css
Labels: local-verified, GitLab linked

#1204 feat(tags): improve tag filtering logic
  frontend/src/components/tags/TagList.vue
  frontend/src/components/tags/TagSidebar.vue
Labels: local-verified, GitLab linked
